# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gmail', models.CharField(max_length=128)),
                ('affiliation', models.CharField(blank=True, max_length=256, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
