# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-18 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=32, unique=True)),
                ('gmail', models.CharField(max_length=128)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
